services:
  backend:
    image: yaroslav333/dyplom:latest
    container_name: flask-app
    ports:
      - "5088:5088"
    environment:
      - FLASK_ENV=development
      - MONGO_URL=mongodb://mongodb:27017/solar_system
    depends_on:
      - mongodb

  generator:
    image: yaroslav333/dyplom:latest
    container_name: Libsodium_real_time_data_cypher
    command: python Libsodium_real_time_data_cypher.py
    environment:
      - MONGO_URL=mongodb://mongodb:27017/solar_system
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
